name: Test

on:
  push:
    branches:
      - master
      - dev
      - mac
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        python -m pip install uv

    - name: Install dependencies with uv
      run: |
        uv pip install .

    - name: Set PYTHONPATH (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

    - name: Set PYTHONPATH (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "PYTHONPATH=$PWD;$env:PYTHONPATH" >> $env:GITHUB_ENV

    - name: Run pytest
      run: |
        PYTHONPATH=$PYTHONPATH uv run pytest tests/ --maxfail=5 --disable-warnings
