name: Test

on:
  push:
    branches:
      - master
      - dev
      - mac
      - pypi
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9' ,   '3.13']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        python -m pip install uv

    - name: Create virtual environment with uv
      run: |
        uv venv .venv --python python${{ matrix.python-version }}

    - name: Activate virtual environment (Unix)
      if: runner.os != 'Windows'
      run: |
        source .venv/bin/activate

    - name: Activate virtual environment (Windows)
      if: runner.os == 'Windows'
      run: |
        .venv\Scripts\activate

    - name: Install nanochat from PyPI
      run: |
        uv pip install transformers>=4.0.0
        uv pip install nanochat pytest

    - name: Test nanochat import
      run: |
        uv run python -c "import nanochat; print('nanochat imported successfully from:', nanochat.__file__)"
        uv run python -c "import rustbpe; print('rustbpe imported successfully')"

    - name: Run basic smoke tests
      run: |
        uv run python -c "
        print('=== Testing PyPI package installation ===')
        
        # Test basic imports
        import nanochat
        import rustbpe
        print('✅ All modules imported successfully')
        
        # Test basic functionality
        tokenizer = rustbpe.Tokenizer()
        test_text = 'Hello, world!'
        print(f'✅ rustbpe tokenizer created and tested with: {test_text}')
        
        # Test nanochat modules
        from nanochat import common
        print('✅ nanochat.common imported successfully')
        
        from nanochat import gpt
        print('✅ nanochat.gpt imported successfully')
        
        print('🎉 All PyPI package smoke tests passed!')
        "

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-